language: java
jdk:
  - oraclejdk8
before_install: cd Satoru
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: satorusan
  on:
    repo: dlameri/Satoru
